import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  IconSearch,
  IconCommercial,
  IconMenu,
  IconResidential,
  IconCaret,
  IconBed,
  IconBath,
  IconHeart,
  IconCaretInCircle,
  IconInstagram,
  IconFacebook,
  IconTwitter,
  IconAccount,
  IconAgency,
  IconBroker,
  IconConfirmationCheckmark,
  IconPinterest,
} from "@/components/elements/Icons";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white h-screen">
        <h1 className="text-black">gashdgsg</h1>
        <div>
          <IconMenu />
          <IconResidential />
          <IconSearch />
          <IconCommercial />
          <IconCaret direction="up" />
          <IconBed />
          <IconBath />
          <IconHeart />
          <IconCaretInCircle />
          <IconInstagram fill="black" />
          <IconFacebook fill="black" />
          <IconPinterest fill="black" />
          <IconTwitter fill="black" />
          <IconAgency />
          <IconBroker />
          <IconAccount />
          <IconConfirmationCheckmark />
        </div>
      </main>
    </>
  );
}
