import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  IconSearch,
  IconCommercial,
  IconMenu,
  IconResidential,
  IconCaret,
  IconBed,
  IconBath,
  IconHeart,
  IconCaretInCircle,
  IconInstagram,
  IconFacebook,
  IconTwitter,
  IconAccount,
  IconAgency,
  IconBroker,
  IconConfirmationCheckmark,
  IconPinterest,
} from "@/components/elements/Icons";
import Section from "@/components/elements/Section";
import Layout from "@/components/global/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Layout title={"Home Page"} description={"home page Cribs KGL"}>
        {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
        <main className=" bg-white h-screen">
          <h1 className="text-black">gashdgsg</h1>

          <Section
            as="div"
            display="flex"
            className="justify-center items-center bg-red-400"
          >
            <div>hsjkhdksdghfgjsdgfhsdhf</div>
          </Section>
        </main>
      </Layout>
    </>
  );
}
